### ISSUE TITLE
repository内で使用するnodeのversionを明示して欲しい

### ISSUE THREAD

**Issue by t-ohkoshi** [hwavy/React-Handson#3]
- 使用するnodeのversionが不明だったので、node-versionのようなファイルを作成してversionを明示して欲しい

**Comment by koemigg** [comment]
`nodebrew`消してasdfでnodejsを入れ直しました。
`asdf local nodejs 16.10.0`したら勝手に`.tool-versions`ができた感じなんですがこれでいいでしょうか？
